version: '3'

volumes:
  code_share:

services:
 nginx:
   build: ./nginx
   ports:
     - 80:80
   volumes:
     - code_share:/var/www
   depends_on:
     - php
 php:
   build: ./php
   volumes:
    - code_share:/var/www
   depends_on:
     - db
 db:
   image: mariadb:latest
   restart: always
   ports:
     - 3306:3306
   volumes:
     - ./mysql:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: secret
     TZ: 'Asia/Tokyo'
 phpmyadmin:
   depends_on:
     - db
   image: phpmyadmin/phpmyadmin:latest
   restart: always
   ports:
     - 8888:80
   environment:
     PMA_HOST: db
   links:
     - db